# Generated by Django 4.2.2 on 2023-10-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_skills_percentage_alter_skills_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='value',
            field=models.IntegerField(),
        ),
    ]
