# Generated by Django 4.2.2 on 2023-10-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactus_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
