# Generated by Django 4.2.2 on 2023-10-27 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_portfolio_description_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='media_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='portfolio_media/'),
            preserve_default=False,
        ),
    ]
