# Generated by Django 4.2.2 on 2023-10-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_portfolio_options_remove_portfolio_image_and_more'),
    ]

    operations = [
    ]
