# Generated by Django 4.2.2 on 2023-10-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20231027_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='media_file',
            field=models.ImageField(upload_to='portfolio_media/'),
        ),
    ]
