# Generated by Django 4.2.2 on 2023-10-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_portfolio_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='media_file',
            field=models.FileField(upload_to='portfolio_media/'),
        ),
    ]
