# Generated by Django 4.2.2 on 2023-10-27 15:36

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_portfolio_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='media_file',
            field=models.FileField(upload_to='portfolio_media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif', 'mp4', 'webm'])]),
        ),
    ]
