# Generated by Django 4.2.2 on 2023-10-27 15:51

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_portfolio_media_type_alter_portfolio_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='media_type',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='media_file',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
