# Generated by Django 4.2.2 on 2023-10-27 16:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_portfolio_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='media_file',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
