# Generated by Django 4.2.2 on 2023-10-27 16:30

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_portfolio_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='media_file',
            field=froala_editor.fields.FroalaField(blank='True', null=True),
        ),
    ]
