# Generated by Django 4.2.2 on 2023-10-27 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_portfolio_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Portfolio Categories',
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='media_file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
