# Generated by Django 4.2.2 on 2023-10-27 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_resume_alter_portfolio_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='point',
            new_name='list1',
        ),
        migrations.AddField(
            model_name='resume',
            name='list2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='list3',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='list4',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='list5',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
