# Generated by Django 4.2.2 on 2023-10-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_resume_list6_resume_list7_alter_resume_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='body',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
