# Generated by Django 4.2.2 on 2023-10-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_resume_list10_resume_list11_resume_list12_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'AboutDrop',
                'verbose_name_plural': 'Profile Picture',
            },
        ),
    ]
