# Generated by Django 4.2.2 on 2023-10-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_about_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
