# Generated by Django 4.2.2 on 2023-10-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_degree_about_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.AddField(
            model_name='about',
            name='point',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
