# Generated by Django 4.2.2 on 2023-10-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_about_phone_about_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='point',
            new_name='point1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='address',
        ),
        migrations.RemoveField(
            model_name='about',
            name='age',
        ),
        migrations.RemoveField(
            model_name='about',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='about',
            name='email',
        ),
        migrations.RemoveField(
            model_name='about',
            name='freelance',
        ),
        migrations.AddField(
            model_name='about',
            name='point2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='point3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='point4',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='point5',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='point6',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='point7',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='point8',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
