# Generated by Django 4.2.2 on 2023-10-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_contactme_alter_contact_address_alter_contact_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMe',
            new_name='Mydetails',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact Me'},
        ),
        migrations.AlterModelOptions(
            name='mydetails',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Details'},
        ),
    ]
