# Generated by Django 4.2.2 on 2023-10-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_address_contact_name_remove_contact_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
