# Generated by Django 4.2.2 on 2023-10-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
